Fixing It All (almost)
-Learning next button fixed (Didn't turn off on start)
-Learning words videos fixed (VideoManager was missing)
-Learning words progression fixed (Used to cut off before last word)
Error: Playing a learning mode twice results in errors

-Terrain checkboxes hidden, tutorial still shown
-Camp/Fire and Play/Ground SHOULD work with double input and video displays (not sure how the double input code is connected so Johnathan may have to check)
-Screenshot button moved to a better location

-Create data functions for quizzes and screenshot fixed to save timestamp (was missing a /)
-Quizzes should now save score in database (Was using old database script)
-Quiz skip button fixed (Not stretched out anymore)

-Removed scripts for old database